import os

os.environ["TRANSFORMERS_CACHE"] = "/projects/bhuang/.cache/huggingface/transformers"
os.environ["HF_DATASETS_CACHE"] = "/projects/bhuang/.cache/huggingface/datasets"
# os.environ["OMP_NUM_THREADS"] = "1"
# os.environ["TOKENIZERS_PARALLELISM"] = "false"
# os.environ["BITSANDBYTES_NOWELCOME"] = "1"
os.environ["CUDA_VISIBLE_DEVICES"] = "1"

# from run_speech_recognition_seq2seq_streaming_b import main
from run_speech_recognition_seq2seq_c import main

main(
    [
        "--model_name_or_path",
        "openai/whisper-large-v3",
        "--use_auth_token",
        "--apply_spec_augment",
        "--train_file",
        # "/projects/bhuang/corpus/speech/nemo_manifests/final/2023-11-13/train_asr_processed_dedup256_processed_cleaned.json",
        "/projects/bhuang/corpus/speech/nemo_manifests/final/2023-11-13/train_asr_processed_dedup256_processed_cleaned_head1024.json",
        "--validation_file",
        # "/projects/bhuang/corpus/speech/nemo_manifests/final/2023-11-13/test_asr_mcv13_manifest_normalized_pnc.json",
        "/projects/bhuang/corpus/speech/nemo_manifests/final/2023-11-13/test_asr_mcv13_manifest_normalized_pnc_head128.json",
        "--audio_column_name",
        "audio_filepath",
        # "--streaming",
        # "--dispatch_batches",
        # "false",
        # "--num_shards",
        # "16",
        "--max_duration_in_seconds",
        "30",
        "--apply_audio_augmentation",
        "--background_noise_dir",
        "/home/bhuang/corpus/speech/public/musan_wo_speech",
        "--audio_augmentation_prob",
        "0.4",
        "--do_lower_case",
        "false",
        # "--do_normalize_eval",
        # "false",
        "--language",
        "french",
        "--task",
        "transcribe",
        "--preprocessing_num_workers",
        "32",
        "--dataloader_num_workers",
        "1",
        "--output_dir",
        "./outputs/tmp_debug",
        "--overwrite_output_dir",
        "--max_steps",
        "10319",
        "--per_device_train_batch_size",
        "32",
        "--per_device_eval_batch_size",
        "16",
        "--gradient_accumulation_steps",
        "4",
        "--optim",
        "adamw_bnb_8bit",
        "--adam_beta2",
        "0.98",
        "--learning_rate",
        "4.375e-6",
        "--warmup_ratio",
        "0.05",
        "--logging_steps",
        "1",
        "--evaluation_strategy",
        "no",
        # "steps",
        "--eval_steps",
        "500",
        "--save_strategy",
        "no",
        "--metric_for_best_model",
        "wer",
        "--greater_is_better",
        "false",
        "--load_best_model_at_end",
        "--freeze_feature_encoder",
        "false",
        "--fp16",
        "--use_cache",
        "false",
        "--gradient_checkpointing",
        "--predict_with_generate",
        "--generation_num_beams",
        "1",
        "--generation_max_length",
        "225",
        "--remove_unused_columns",
        "false",
        "--do_train",
        "--do_eval",
        "--report_to",
        "none",
    ]
)

